// AUTO-GENERATED: All active exercises from database
// Do not edit manually - regenerate using: node scripts/generate-exercise-menu.js

export const AI_EXERCISE_MENU = {
  'back': [
    'archer pull up',
    'assisted parallel close grip pull-up',
    'assisted pull-up',
    'assisted standing pull-up',
    'band assisted pull-up',
    'band shrug',
    'barbell bent arm pullover',
    'barbell bent over row',
    'barbell decline bent arm pullover',
    'barbell decline wide-grip pullover',
    'barbell incline row',
    'barbell one arm bent over row',
    'barbell pendlay row',
    'barbell pullover',
    'barbell pullover to press',
    'barbell reverse grip bent over row',
    'barbell reverse grip incline bench row',
    'barbell shrug',
    'bodyweight standing close-grip row',
    'bodyweight standing row',
    'cable bar lateral pulldown',
    'cable cross-over lateral pulldown',
    'cable incline bench row',
    'cable incline pushdown',
    'cable one arm pulldown',
    'cable palm rotational row',
    'cable pulldown',
    'cable rear pulldown',
    'cable rope seated row',
    'cable seated row',
    'cable seated wide-grip row',
    'cable shrug',
    'cable squat row (with rope attachment)',
    'cable standing row (v-bar)',
    'cable straight arm pulldown',
    'cable twisting pull',
    'cable underhand pulldown',
    'cable upper row',
    'chin-up',
    'chin-ups (narrow parallel grip)',
    'close grip chin-up',
    'dumbbell bent over row',
    'dumbbell decline shrug',
    'dumbbell decline shrug alternate',
    'dumbbell incline row',
    'dumbbell incline shrug',
    'dumbbell one arm bent-over row',
    'dumbbell shrug',
    'ez bar lying bent arms pullover',
    'front lever reps',
    'inverted row',
    'inverted row bent knees',
    'inverted row on bench',
    'inverted row with straps',
    'kettlebell alternating row',
    'kettlebell one arm row',
    'kipping pull up',
    'l-pull-up',
    'lat pulldown cable',
    'lat pulldown machine',
    'lever assisted chin-up',
    'lever bent over row',
    'lever gripless shrug',
    'lever one arm bent over row',
    'lever pullover',
    'lever shrug',
    'mixed grip chin-up',
    'muscle up',
    'pull-up',
    'rear pull-up',
    'resistance band seated straight back row',
    'reverse grip machine lat pulldown',
    'seated row machine',
    'smith bent over row',
    't-bar row machine',
    'wide grip pull-up',
  ],
  'cardio': [
    'air bike',
    'back and forth step',
    'bear crawl',
    'cycle cross trainer',
    'elliptical machine',
    'high knee against wall',
    'jump rope',
    'mountain climber',
    'recumbent bike',
    'rowing machine',
    'run',
    'ski step',
    'stationary bike',
    'treadmill',
    'walking on incline treadmill',
    'walking on stepmill',
  ],
  'chest': [
    'archer push up',
    'band bench press',
    'barbell bench press',
    'barbell decline bench press',
    'barbell decline pullover',
    'barbell decline wide-grip press',
    'barbell front raise and pullover',
    'barbell guillotine bench press',
    'barbell incline bench press',
    'barbell reverse grip decline bench press',
    'barbell reverse grip incline bench press',
    'barbell wide bench press',
    'barbell wide reverse grip bench press',
    'cable bench press',
    'cable decline fly',
    'cable fly',
    'cable incline bench press',
    'chest dip',
    'chest press machine',
    'deep push up',
    'dumbbell around pullover',
    'dumbbell bench press',
    'dumbbell decline bench press',
    'dumbbell decline fly',
    'dumbbell decline hammer press',
    'dumbbell decline twist fly',
    'dumbbell fly',
    'dumbbell incline alternate press',
    'dumbbell incline bench press',
    'dumbbell incline fly',
    'dumbbell incline hammer press',
    'dumbbell incline palm-in press',
    'dumbbell incline twisted flyes',
    'dumbbell lying hammer press',
    'dumbbell pullover',
    'dumbbell reverse bench press',
    'dumbbell straight arm pullover',
    'floor fly (with barbell)',
    'floor press barbell',
    'incline scapula push up',
    'medicine ball chest pass',
    'medicine ball chest push single response',
    'pec deck machine',
    'push-up',
    'push-up (wall)',
    'resistance band seated chest press',
    'smith bench press',
    'smith decline bench press',
    'smith incline bench press',
    'superman push-up',
  ],
  'full body': [
    'barbell clean and press',
    'burpee',
    'dumbbell burpee',
    'jack burpee',
    'kettlebell hang clean',
    'kettlebell sumo high pull',
    'kettlebell swing',
    'medicine ball overhead slam',
    'thruster barbell',
  ],
  'lower arms': [
    'barbell palms down wrist curl over a bench',
    'barbell palms up wrist curl over a bench',
    'barbell reverse wrist curl',
    'barbell standing back wrist curl',
    'barbell wrist curl',
    'cable reverse wrist curl',
    'cable wrist curl',
    'dumbbell finger curls',
    'dumbbell reverse wrist curl',
  ],
  'lower legs': [
    'barbell floor calf raise',
    'barbell seated calf raise',
    'barbell standing calf raise',
    'barbell standing leg calf raise',
    'barbell standing rocking leg calf raise',
    'bodyweight standing calf raise',
    'cable standing calf raise',
    'cable standing one leg calf raise',
    'donkey calf raise',
    'dumbbell seated calf raise',
    'dumbbell seated one leg calf raise',
    'dumbbell seated one leg calf raise - hammer grip',
    'dumbbell seated one leg calf raise - palm up',
    'dumbbell single leg calf raise',
    'dumbbell standing calf raise',
    'hack calf raise',
    'lever donkey calf raise',
    'lever seated calf raise',
    'lever standing calf raise',
    'sled calf press on leg press',
    'sled forward angled calf raise',
    'sled one leg calf press on leg press',
    'smith reverse calf raises',
  ],
  'shoulders': [
    'band twisting overhead press',
    'barbell front raise',
    'barbell incline shoulder raise',
    'barbell rear delt raise',
    'barbell rear delt row',
    'barbell seated behind head military press',
    'barbell seated overhead press',
    'barbell standing bradford press',
    'barbell standing front raise over head',
    'barbell upright row',
    'barbell wide-grip upright row',
    'battling ropes',
    'cable cross-over reverse fly',
    'cable lateral raise',
    'cable one arm lateral raise',
    'dumbbell alternate side press',
    'dumbbell arnold press',
    'dumbbell bench seated press',
    'dumbbell cuban press',
    'dumbbell front raise',
    'dumbbell incline raise',
    'dumbbell incline shoulder raise',
    'dumbbell incline t-raise',
    'dumbbell incline y-raise',
    'dumbbell lateral raise',
    'dumbbell push press',
    'dumbbell raise',
    'dumbbell rear delt raise',
    'dumbbell rear fly',
    'dumbbell rear lateral raise',
    'dumbbell reverse fly',
    'dumbbell rotation reverse fly',
    'dumbbell scott press',
    'dumbbell seated front raise',
    'dumbbell seated shoulder press',
    'dumbbell standing alternate overhead press',
    'dumbbell standing alternate raise',
    'dumbbell standing overhead press',
    'dumbbell upright row',
    'dumbbell w-press',
    'landmine lateral raise',
    'lever seated reverse fly (parallel grip)',
    'overhead press cable',
    'resistance band seated shoulder press',
    'reverse fly machine',
    'shoulder press machine',
    'smith seated shoulder press',
    'smith shoulder press',
    'smith upright row',
  ],
  'upper arms': [
    'advanced dips',
    'barbell alternate biceps curl',
    'barbell close-grip bench press',
    'barbell curl',
    'barbell drag curl',
    'barbell incline close grip bench press',
    'barbell incline reverse-grip press',
    'barbell jm bench press',
    'barbell lying close-grip press',
    'barbell lying close-grip triceps extension',
    'barbell lying extension',
    'barbell lying preacher curl',
    'barbell preacher curl',
    'barbell prone incline curl',
    'barbell reverse close-grip bench press',
    'barbell reverse curl',
    'barbell reverse preacher curl',
    'barbell standing concentration curl',
    'barbell standing wide-grip curl',
    'biceps narrow pull-ups',
    'biceps pull-up',
    'cable curl',
    'cable kickback',
    'cable one arm tricep pushdown',
    'cable preacher curl',
    'cable pushdown',
    'cable pushdown (with rope attachment)',
    'cable reverse-grip pushdown',
    'cable squatting curl',
    'cable triceps pushdown (v-bar)',
    'close-grip push-up',
    'diamond push-up',
    'dumbbell bicep curl lunge with bowling motion',
    'dumbbell biceps curl squat',
    'dumbbell concentration curl',
    'dumbbell forward lunge triceps extension',
    'dumbbell hammer curl',
    'dumbbell kickback',
    'dumbbell lunge with bicep curl',
    'dumbbell neutral grip bench press',
    'dumbbell palms in incline bench press',
    'dumbbell preacher curl',
    'dumbbell twisting bench press',
    'elbow dips',
    'exercise ball dip',
    'ez barbell close-grip curl',
    'ez barbell curl',
    'ez barbell jm bench press',
    'ez barbell seated curls',
    'ez barbell spider curl',
    'ez-bar close-grip bench press',
    'handstand push-up',
    'lever overhand triceps dip',
    'lever seated dip',
    'resistance band seated biceps curl',
    'smith close-grip bench press',
    'smith machine bicep curl',
    'triceps dip',
    'triceps dip (bench leg)',
  ],
  'upper legs': [
    'band one arm single leg split squat',
    'band single leg split squat',
    'band squat row',
    'band straight leg deadlift',
    'barbell bench front squat',
    'barbell bench squat',
    'barbell clean-grip front squat',
    'barbell deadlift',
    'barbell front chest squat',
    'barbell front squat',
    'barbell full squat',
    'barbell full zercher squat',
    'barbell good morning',
    'barbell hack squat',
    'barbell high bar squat',
    'barbell jefferson squat',
    'barbell jump squat',
    'barbell lateral lunge',
    'barbell low bar squat',
    'barbell lunge',
    'barbell narrow stance squat',
    'barbell one arm side deadlift',
    'barbell one leg squat',
    'barbell overhead squat',
    'barbell rear lunge',
    'barbell romanian deadlift',
    'barbell side split squat',
    'barbell side split squat wide',
    'barbell single leg deadlift',
    'barbell single leg split squat',
    'barbell speed squat',
    'barbell split squat',
    'barbell squat (on knees)',
    'barbell squat jump step rear lunge',
    'barbell straight leg deadlift',
    'barbell sumo deadlift',
    'barbell wide squat',
    'barbell zercher squat',
    'belt squat',
    'bodyweight drop jump squat',
    'cable assisted inverse leg curl',
    'cable deadlift',
    'cable hip adduction',
    'curtsey squat',
    'dumbbell bench squat',
    'dumbbell contralateral forward lunge',
    'dumbbell deadlift',
    'dumbbell goblet squat',
    'dumbbell lunge',
    'dumbbell lying femoral',
    'dumbbell plyo squat',
    'dumbbell rear lunge',
    'dumbbell romanian deadlift',
    'dumbbell single leg deadlift',
    'dumbbell single leg split squat',
    'dumbbell single leg squat',
    'dumbbell squat',
    'dumbbell step-up lunge',
    'dumbbell step-up split squat',
    'dumbbell stiff leg deadlift',
    'dumbbell straight leg deadlift',
    'dumbbell supported squat',
    'farmers walk',
    'forward lunge',
    'frankenstein squat',
    'glute-ham raise',
    'hip abduction machine',
    'hip adduction machine',
    'inverse leg curl (bench support)',
    'inverse leg curl (on pull-up cable machine)',
    'jump squat',
    'kettlebell front squat',
    'kettlebell goblet squat',
    'kettlebell pistol squat',
    'leg extension machine',
    'lever alternate leg press',
    'lever kneeling leg curl',
    'lever lying two-one leg curl',
    'lying leg curl machine',
    'one leg squat',
    'rear decline bridge',
    'resistance band hip thrusts on knees',
    'resistance band leg extension',
    'seated leg curl machine',
    'self assisted inverse leg curl',
    'sled 45 degrees one leg press',
    'sled 45° leg press',
    'sled 45° leg wide press',
    'sled closer hack squat',
    'sled hack squat',
    'sled lying squat',
    'smith deadlift',
    'smith full squat',
    'smith hack squat',
    'smith single leg split squat',
    'smith squat',
    'trap bar deadlift',
    'walking lunge',
  ],
  'waist': [
    '3/4 sit-up',
    'back extension on exercise ball',
    'balance board',
    'bodyweight incline side plank',
    'cable kneeling crunch',
    'cable reverse crunch',
    'cable seated crunch',
    'cable side crunch',
    'cable standing crunch',
    'cable tuck reverse crunch',
    'cross body crunch',
    'crunch (hands overhead)',
    'crunch floor',
    'dead bug',
    'decline crunch',
    'dumbbell side plank with rear fly',
    'elbow-to-knee',
    'exercise ball prone leg raise',
    'frog crunch',
    'front plank with twist',
    'ghd back extension',
    'ghd sit-up',
    'hanging leg raise',
    'hyperextension',
    'hyperextension (on bench)',
    'knee touch crunch',
    'leg pull in flat bench',
    'lever back extension',
    'lever kneeling twist',
    'lever seated leg raise crunch',
    'oblique crunch',
    'reverse crunch',
    'reverse hyperextension machine',
    'sit-up',
  ],
};

// Total: 423 active exercises across 10 categories

/**
 * Get a formatted string of exercises for AI prompt
 * Returns ALL available exercises organized by category
 */
export function getExercisePromptList(): string {
  let prompt = '🏋️ AVAILABLE EXERCISES - Use EXACT names from this list:\n\n';
  
  // Use ALL exercises from the database
  Object.entries(AI_EXERCISE_MENU).forEach(([category, exercises]) => {
    prompt += `${category.toUpperCase()} (${exercises.length}):\n`;
    prompt += exercises.join(', ') + '\n\n';
  });
  
  prompt += '⚠️ CRITICAL RULES:\n';
  prompt += '1. Use ONLY exercises from the list above (EXACT names, case-insensitive)\n';
  prompt += '2. Do NOT make up exercise names\n';
  prompt += '3. Do NOT modify or abbreviate names\n';
  prompt += '4. Choose 4-6 exercises that work well together\n';
  
  return prompt;
}

/**
 * Get all exercise names as a flat array for validation
 */
export function getAllExerciseNames(): string[] {
  return Object.values(AI_EXERCISE_MENU).flat();
}
